In [1]:
import numpy as np
import pandas as pd

In [2]:
concrete_data = pd.read_csv('https://cocl.us/concrete_data')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
concrete_data.shape

(1030, 9)

In [4]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
# Split the data into predictors n target

concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns!= 'Strength']]
target = concrete_data['Strength']

In [7]:
predictors_norm = (predictors - predictors.mean())/predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [8]:
# Number of predictors

n_cols = predictors_norm.shape[1]
n_cols

8

In [9]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [10]:
# Regression Model

def regression_model():
    model = Sequential()
    model.add(Dense(10, activation ='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    model.compile(optimizer='adam', loss='mean_squared_error'
)
    return model

In [11]:
# split the data into trg n test sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(predictors,
target, test_size=0.3, random_state=1)

In [12]:
# Model Create

model = regression_model()

In [13]:
# Model Fit

epochs = 100
model.fit(X_train, y_train, epochs=epochs, verbose=1)

Epoch 1/100
721/721 [==============================] - 1s 712us/step - loss: 4192.2123
Epoch 2/100
721/721 [==============================] - 0s 303us/step - loss: 3578.6059
Epoch 3/100
721/721 [==============================] - 0s 417us/step - loss: 3076.7341
Epoch 4/100
721/721 [==============================] - 0s 468us/step - loss: 2645.7748
Epoch 5/100
721/721 [==============================] - 0s 331us/step - loss: 2226.3990
Epoch 6/100
721/721 [==============================] - 0s 360us/step - loss: 2007.8142
Epoch 7/100
721/721 [==============================] - 0s 421us/step - loss: 1699.6592
Epoch 8/100
721/721 [==============================] - 0s 326us/step - loss: 1430.2354
Epoch 9/100
721/721 [==============================] - 0s 309us/step - loss: 1243.9100
Epoch 10/100
721/721 [==============================] - 0s 333us/step - loss: 1096.7929
Epoch 11/100
721/721 [==============================] - 0s 308us/step - loss: 942.8647
Epoch 12/100
721/721 [==============================] - 0s 329us/step - loss: 823.8700
Epoch 13/100
721/721 [==============================] - 0s 304us/step - loss: 722.0764
Epoch 14/100
721/721 [==============================] - 0s 303us/step - loss: 637.9984
Epoch 15/100
721/721 [==============================] - 0s 307us/step - loss: 557.6438
Epoch 16/100
721/721 [==============================] - 0s 310us/step - loss: 491.2266
Epoch 17/100
721/721 [==============================] - 0s 367us/step - loss: 441.5377
Epoch 18/100
721/721 [==============================] - 0s 333us/step - loss: 393.0533
Epoch 19/100
721/721 [==============================] - 0s 279us/step - loss: 355.5885
Epoch 20/100
721/721 [==============================] - 0s 306us/step - loss: 319.3328
Epoch 21/100
721/721 [==============================] - 0s 299us/step - loss: 286.2304
Epoch 22/100
721/721 [==============================] - 0s 334us/step - loss: 263.1936
Epoch 23/100
721/721 [==============================] - 0s 301us/step - loss: 241.5942
Epoch 24/100
721/721 [==============================] - 0s 302us/step - loss: 222.9464
Epoch 25/100
721/721 [==============================] - 0s 276us/step - loss: 204.9697
Epoch 26/100
721/721 [==============================] - 0s 331us/step - loss: 190.5505
Epoch 27/100
721/721 [==============================] - 0s 306us/step - loss: 177.0551
Epoch 28/100
721/721 [==============================] - 0s 311us/step - loss: 167.7353
Epoch 29/100
721/721 [==============================] - 0s 295us/step - loss: 158.3626
Epoch 30/100
721/721 [==============================] - 0s 332us/step - loss: 150.5572
Epoch 31/100
721/721 [==============================] - 0s 304us/step - loss: 144.9939
Epoch 32/100
721/721 [==============================] - 0s 303us/step - loss: 138.6022
Epoch 33/100
721/721 [==============================] - 0s 304us/step - loss: 141.4621
Epoch 34/100
721/721 [==============================] - 0s 358us/step - loss: 134.3188
Epoch 35/100
721/721 [==============================] - 0s 499us/step - loss: 131.7704 0s - loss: 123.3
Epoch 36/100
721/721 [==============================] - 0s 559us/step - loss: 131.5728
Epoch 37/100
721/721 [==============================] - 0s 586us/step - loss: 130.2208
Epoch 38/100
721/721 [==============================] - 1s 749us/step - loss: 124.6567 0s - loss: 11
Epoch 39/100
721/721 [==============================] - 0s 499us/step - loss: 123.5975
Epoch 40/100
721/721 [==============================] - 0s 307us/step - loss: 125.5007
Epoch 41/100
721/721 [==============================] - 0s 301us/step - loss: 121.3323
Epoch 42/100
721/721 [==============================] - 0s 305us/step - loss: 120.6035
Epoch 43/100
721/721 [==============================] - 0s 339us/step - loss: 118.7793
Epoch 44/100
721/721 [==============================] - 0s 361us/step - loss: 118.5155
Epoch 45/100
721/721 [==============================] - 0s 283us/step - loss: 118.4824
Epoch 46/100
721/721 [==============================] - 0s 334us/step - loss: 115.7895
Epoch 47/100
721/721 [==============================] - 0s 307us/step - loss: 116.4587
Epoch 48/100
721/721 [==============================] - 0s 300us/step - loss: 115.2123
Epoch 49/100
721/721 [==============================] - 0s 389us/step - loss: 116.5119
Epoch 50/100
721/721 [==============================] - 0s 331us/step - loss: 121.4988
Epoch 51/100
721/721 [==============================] - 0s 332us/step - loss: 116.3349
Epoch 52/100
721/721 [==============================] - 0s 451us/step - loss: 113.6764
Epoch 53/100
721/721 [==============================] - 0s 308us/step - loss: 115.5289
Epoch 54/100
721/721 [==============================] - 0s 556us/step - loss: 115.1256
Epoch 55/100
721/721 [==============================] - 0s 357us/step - loss: 111.4277
Epoch 56/100
721/721 [==============================] - 0s 329us/step - loss: 112.1058
Epoch 57/100
721/721 [==============================] - 0s 337us/step - loss: 115.3456
Epoch 58/100
721/721 [==============================] - 0s 325us/step - loss: 110.1261
Epoch 59/100
721/721 [==============================] - 0s 303us/step - loss: 113.9428
Epoch 60/100
721/721 [==============================] - 0s 307us/step - loss: 113.0082
Epoch 61/100
721/721 [==============================] - 0s 328us/step - loss: 109.7527
Epoch 62/100
721/721 [==============================] - 0s 279us/step - loss: 110.8253
Epoch 63/100
721/721 [==============================] - 0s 328us/step - loss: 111.3461
Epoch 64/100
721/721 [==============================] - 0s 333us/step - loss: 115.2768
Epoch 65/100
721/721 [==============================] - 0s 278us/step - loss: 122.3325
Epoch 66/100
721/721 [==============================] - 0s 358us/step - loss: 110.5461
Epoch 67/100
721/721 [==============================] - 0s 303us/step - loss: 113.3506
Epoch 68/100
721/721 [==============================] - 0s 309us/step - loss: 110.8253
Epoch 69/100
721/721 [==============================] - 0s 323us/step - loss: 110.9359
Epoch 70/100
721/721 [==============================] - 0s 336us/step - loss: 111.6336
Epoch 71/100
721/721 [==============================] - 0s 328us/step - loss: 109.1862
Epoch 72/100
721/721 [==============================] - 0s 413us/step - loss: 111.6010
Epoch 73/100
721/721 [==============================] - 0s 309us/step - loss: 106.4062
Epoch 74/100
721/721 [==============================] - 0s 301us/step - loss: 110.0926
Epoch 75/100
721/721 [==============================] - 0s 309us/step - loss: 107.5978
Epoch 76/100
721/721 [==============================] - 0s 472us/step - loss: 108.3573
Epoch 77/100
721/721 [==============================] - 0s 327us/step - loss: 107.2118
Epoch 78/100
721/721 [==============================] - 0s 304us/step - loss: 108.2291
Epoch 79/100
721/721 [==============================] - 0s 304us/step - loss: 107.9811
Epoch 80/100
721/721 [==============================] - 0s 308us/step - loss: 110.1734
Epoch 81/100
721/721 [==============================] - 0s 337us/step - loss: 110.9996
Epoch 82/100
721/721 [==============================] - 0s 357us/step - loss: 106.1737
Epoch 83/100
721/721 [==============================] - 0s 357us/step - loss: 106.4769
Epoch 84/100
721/721 [==============================] - 0s 329us/step - loss: 107.8176
Epoch 85/100
721/721 [==============================] - 0s 303us/step - loss: 105.7740
Epoch 86/100
721/721 [==============================] - 0s 332us/step - loss: 108.5116
Epoch 87/100
721/721 [==============================] - 0s 308us/step - loss: 107.8682
Epoch 88/100
721/721 [==============================] - 0s 306us/step - loss: 108.9371
Epoch 89/100
721/721 [==============================] - 0s 331us/step - loss: 105.8655
Epoch 90/100
721/721 [==============================] - 0s 312us/step - loss: 107.1971
Epoch 91/100
721/721 [==============================] - 0s 309us/step - loss: 106.8327
Epoch 92/100
721/721 [==============================] - 0s 274us/step - loss: 108.4116
Epoch 93/100
721/721 [==============================] - 0s 301us/step - loss: 108.1968
Epoch 94/100
721/721 [==============================] - 0s 331us/step - loss: 108.4144
Epoch 95/100
721/721 [==============================] - 0s 308us/step - loss: 106.3595
Epoch 96/100
721/721 [==============================] - 0s 301us/step - loss: 105.7175
Epoch 97/100
721/721 [==============================] - 0s 306us/step - loss: 105.5331
Epoch 98/100
721/721 [==============================] - 0s 306us/step - loss: 107.5492
Epoch 99/100
721/721 [==============================] - 0s 298us/step - loss: 107.6759
Epoch 100/100
721/721 [==============================] - 0s 329us/step - loss: 113.9968 0s - loss: 125.671 - ETA: 0s - loss: 124.77

In [14]:
# Model Evalation on test data

loss = model.evaluate(X_test, y_test)
y_pred = model.predict(X_test)
loss

309/309 [==============================] - 0s 209us/step

123.37559998151168

In [15]:
# MSE btw the predicted concrete strength and its actual

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print (mse)

123.37560052096728

In [16]:
from sklearn.metrics import mean_squared_error
total_mean_squared_errors = 50
epochs = 50
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size = 0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE " +str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mserror = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mserror)
                                        
mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
sd = np.std(mean_squared_errors)
                                        
print("Mean: "+str(mean))
print("Standard Deviation: "+str(sd))

MSE 1: 248.83004953328845
MSE 2: 158.92857454664113
MSE 3: 112.69886476090811
MSE 4: 102.15636293479155
MSE 5: 90.70823992880418
MSE 6: 81.97861196771024
MSE 7: 84.88584786325596
MSE 8: 68.70138621407419
MSE 9: 69.61155900677431
MSE 10: 57.91713824472767
MSE 11: 47.8769504584155
MSE 12: 43.618543853265955
MSE 13: 51.96119483157655
MSE 14: 47.641759594667306
MSE 15: 42.5514891047308
MSE 16: 35.69674450525574
MSE 17: 38.14851450997263
MSE 18: 36.063523240073984
MSE 19: 37.775443092519026
MSE 20: 38.56022414420415
MSE 21: 34.90751452893501
MSE 22: 34.84058242476874
MSE 23: 33.95044165058815
MSE 24: 37.26862730254633
MSE 25: 35.63115682262433
MSE 26: 40.797309159460966
MSE 27: 35.536740559204496
MSE 28: 32.76171303412675
MSE 29: 38.62755894583792
MSE 30: 35.52589643040135
MSE 31: 33.88771051573522
MSE 32: 31.430258278707857
MSE 33: 32.62919816693056
MSE 34: 36.54261048943479
MSE 35: 35.202756887886515
MSE 36: 38.365757834178346
MSE 37: 34.58612313625496
MSE 38: 36.34640806624033
MSE 39: 34.41862201382041
MSE 40: 29.690445785769366
MSE 44: 40.48260611623622
MSE 45: 39.098633689016204
MSE 46: 37.96037907276339
MSE 47: 36.45725004572699
MSE 48: 37.09756256152897
MSE 49: 36.816177929875145
MSE 50: 36.49709760795519
Mean: 51.38311455992584
Standard Deviation: 37.37695430107562

In [17]:
## Above is the mean and standard deviation of 50 mean squared errors WITH normalized data trained on 100 epochs.
## Mean = 51.38311455992584
# Standard Deviation = 37.37695430107562

In [18]:
## Mean of the mean squared error WITH normalized data on 50 epochs  =  55.0560012109912
## Mean of the mean squared error WITH normalized date on 100 epochs =  51.38311455992584