In [1]:
import numpy as np
import pandas as pd

In [2]:
concrete_data = pd.read_csv('https://cocl.us/concrete_data')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
concrete_data.shape

(1030, 9)

In [4]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
# Split the data into predictors n target

concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns!= 'Strength']]
target = concrete_data['Strength']

In [7]:
predictors_norm = (predictors - predictors.mean())/predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [8]:
# Number of predictors

n_cols = predictors_norm.shape[1]
n_cols

8

In [9]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [10]:
# Regression Model

def regression_model():
    model = Sequential()
    model.add(Dense(10, activation ='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    model.compile(optimizer='adam', loss='mean_squared_error'
)
    return model

In [11]:
# split the data into trg n test sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(predictors,
target, test_size=0.3, random_state=1)

In [12]:
# Model Create

model = regression_model()

In [13]:
# Model Fit

epochs = 100
model.fit(X_train, y_train, epochs=epochs, verbose=1)

Epoch 1/100
721/721 [==============================] - 1s 741us/step - loss: 166400.8571
Epoch 2/100
721/721 [==============================] - 0s 274us/step - loss: 90291.0841
Epoch 3/100
721/721 [==============================] - 0s 303us/step - loss: 41258.6815
Epoch 4/100
721/721 [==============================] - 0s 364us/step - loss: 15785.7837
Epoch 5/100
721/721 [==============================] - 0s 355us/step - loss: 5834.1361
Epoch 6/100
721/721 [==============================] - 0s 308us/step - loss: 3188.1272
Epoch 7/100
721/721 [==============================] - 0s 558us/step - loss: 2750.7413
Epoch 8/100
721/721 [==============================] - 0s 329us/step - loss: 2651.5433
Epoch 9/100
721/721 [==============================] - 0s 390us/step - loss: 2565.6055
Epoch 10/100
721/721 [==============================] - 0s 331us/step - loss: 2480.2794
Epoch 11/100
721/721 [==============================] - 0s 303us/step - loss: 2396.6856
Epoch 12/100
721/721 [==============================] - 0s 330us/step - loss: 2312.4599
Epoch 13/100
721/721 [==============================] - 0s 392us/step - loss: 2229.8495
Epoch 14/100
721/721 [==============================] - 0s 358us/step - loss: 2148.9117
Epoch 15/100
721/721 [==============================] - 0s 333us/step - loss: 2068.1985
Epoch 16/100
721/721 [==============================] - 0s 327us/step - loss: 1990.3670
Epoch 17/100
721/721 [==============================] - 0s 333us/step - loss: 1914.6512
Epoch 18/100
721/721 [==============================] - 0s 638us/step - loss: 1841.0642
Epoch 19/100
721/721 [==============================] - 0s 279us/step - loss: 1771.3482
Epoch 20/100
721/721 [==============================] - 0s 279us/step - loss: 1700.9696
Epoch 21/100
721/721 [==============================] - 0s 308us/step - loss: 1632.40370s - loss: 1691.
Epoch 22/100
721/721 [==============================] - 0s 311us/step - loss: 1568.5699
Epoch 23/100
721/721 [==============================] - 0s 327us/step - loss: 1507.7050
Epoch 24/100
721/721 [==============================] - 0s 306us/step - loss: 1444.8391
Epoch 25/100
721/721 [==============================] - 0s 358us/step - loss: 1386.8407
Epoch 26/100
721/721 [==============================] - 0s 305us/step - loss: 1330.9532
Epoch 27/100
721/721 [==============================] - 0s 307us/step - loss: 1279.0985
Epoch 28/100
721/721 [==============================] - 0s 308us/step - loss: 1226.6843
Epoch 29/100
721/721 [==============================] - 0s 307us/step - loss: 1179.4920
Epoch 30/100
721/721 [==============================] - 0s 380us/step - loss: 1130.9839
Epoch 31/100
721/721 [==============================] - 0s 308us/step - loss: 1083.5706
Epoch 32/100
721/721 [==============================] - 0s 305us/step - loss: 1039.9440
Epoch 33/100
721/721 [==============================] - 0s 327us/step - loss: 1000.1659
Epoch 34/100
721/721 [==============================] - 0s 359us/step - loss: 961.9037
Epoch 35/100
721/721 [==============================] - 0s 331us/step - loss: 924.5680 0s - loss: 912.845
Epoch 36/100
721/721 [==============================] - 0s 303us/step - loss: 886.4276
Epoch 37/100
721/721 [==============================] - 0s 309us/step - loss: 849.4236
Epoch 38/100
721/721 [==============================] - 0s 306us/step - loss: 818.2624
Epoch 39/100
721/721 [==============================] - 0s 299us/step - loss: 784.7179
Epoch 40/100
721/721 [==============================] - 0s 281us/step - loss: 754.1820
Epoch 41/100
721/721 [==============================] - 0s 307us/step - loss: 726.6625
Epoch 42/100
721/721 [==============================] - 0s 302us/step - loss: 699.4188
Epoch 43/100
721/721 [==============================] - 0s 308us/step - loss: 671.0714
Epoch 44/100
721/721 [==============================] - 0s 304us/step - loss: 645.5777
Epoch 45/100
721/721 [==============================] - 0s 379us/step - loss: 620.4791
Epoch 46/100
721/721 [==============================] - 0s 332us/step - loss: 598.6359
Epoch 47/100
721/721 [==============================] - 0s 386us/step - loss: 574.7749
Epoch 48/100
721/721 [==============================] - 0s 307us/step - loss: 553.6643
Epoch 49/100
721/721 [==============================] - 0s 329us/step - loss: 531.4322
Epoch 50/100
721/721 [==============================] - 0s 302us/step - loss: 511.7632
Epoch 51/100
721/721 [==============================] - 0s 280us/step - loss: 493.0886
Epoch 52/100
721/721 [==============================] - 0s 301us/step - loss: 474.7971
Epoch 53/100
721/721 [==============================] - 0s 333us/step - loss: 458.5275
Epoch 54/100
721/721 [==============================] - 0s 661us/step - loss: 438.2452
Epoch 55/100
721/721 [==============================] - 0s 336us/step - loss: 422.0172
Epoch 56/100
721/721 [==============================] - 0s 359us/step - loss: 405.5200
Epoch 57/100
721/721 [==============================] - 0s 306us/step - loss: 390.6134
Epoch 58/100
721/721 [==============================] - ETA: 0s - loss: 375.233 - 0s 279us/step - loss: 375.1178
Epoch 59/100
721/721 [==============================] - 0s 307us/step - loss: 361.3707
Epoch 60/100
721/721 [==============================] - 0s 328us/step - loss: 348.4607
Epoch 61/100
721/721 [==============================] - 0s 329us/step - loss: 333.9371
Epoch 62/100
721/721 [==============================] - 0s 331us/step - loss: 321.2206
Epoch 63/100
721/721 [==============================] - 0s 308us/step - loss: 310.1124
Epoch 64/100
721/721 [==============================] - 0s 332us/step - loss: 297.5126
Epoch 65/100
721/721 [==============================] - 0s 387us/step - loss: 286.1752
Epoch 66/100
721/721 [==============================] - 0s 309us/step - loss: 275.1974
Epoch 67/100
721/721 [==============================] - 0s 300us/step - loss: 264.9822
Epoch 68/100
721/721 [==============================] - 0s 304us/step - loss: 255.6390
Epoch 69/100
721/721 [==============================] - 0s 336us/step - loss: 246.9039 0s - loss: 256.152
Epoch 70/100
721/721 [==============================] - 0s 307us/step - loss: 238.6263
Epoch 71/100
721/721 [==============================] - 0s 331us/step - loss: 232.0083
Epoch 72/100
721/721 [==============================] - 0s 359us/step - loss: 221.7099
Epoch 73/100
721/721 [==============================] - 0s 332us/step - loss: 214.0584
Epoch 74/100
721/721 [==============================] - 0s 361us/step - loss: 208.4183
Epoch 75/100
721/721 [==============================] - 0s 328us/step - loss: 200.7017
Epoch 76/100
721/721 [==============================] - 0s 306us/step - loss: 193.7681
Epoch 77/100
721/721 [==============================] - 0s 305us/step - loss: 187.9910
Epoch 78/100
721/721 [==============================] - 0s 355us/step - loss: 182.7538
Epoch 79/100
721/721 [==============================] - 0s 337us/step - loss: 177.3523
Epoch 80/100
721/721 [==============================] - 0s 326us/step - loss: 173.0142
Epoch 81/100
721/721 [==============================] - 0s 308us/step - loss: 167.6616
Epoch 82/100
721/721 [==============================] - 0s 354us/step - loss: 163.4666
Epoch 83/100
721/721 [==============================] - 0s 277us/step - loss: 159.8710
Epoch 84/100
721/721 [==============================] - 0s 333us/step - loss: 154.9328
Epoch 85/100
721/721 [==============================] - 0s 333us/step - loss: 151.8631
Epoch 86/100
721/721 [==============================] - 0s 413us/step - loss: 148.3324
Epoch 87/100
721/721 [==============================] - 0s 330us/step - loss: 145.7891
Epoch 88/100
721/721 [==============================] - 0s 330us/step - loss: 142.5656
Epoch 89/100
721/721 [==============================] - 0s 333us/step - loss: 142.3074
Epoch 90/100
721/721 [==============================] - 0s 328us/step - loss: 138.5781
Epoch 91/100
721/721 [==============================] - 0s 331us/step - loss: 135.4366
Epoch 92/100
721/721 [==============================] - 0s 312us/step - loss: 133.9604
Epoch 93/100
721/721 [==============================] - 0s 323us/step - loss: 132.3717
Epoch 94/100
721/721 [==============================] - 0s 393us/step - loss: 129.2237
Epoch 95/100
721/721 [==============================] - 0s 354us/step - loss: 128.2422
Epoch 96/100
721/721 [==============================] - 0s 310us/step - loss: 126.5163
Epoch 97/100
721/721 [==============================] - 0s 335us/step - loss: 125.9382
Epoch 98/100
721/721 [==============================] - 0s 356us/step - loss: 123.6038
Epoch 99/100
721/721 [==============================] - 0s 330us/step - loss: 124.4100
Epoch 100/100
721/721 [==============================] - 0s 303us/step - loss: 121.2639

In [14]:
# Model Evalation on test data

loss = model.evaluate(X_test, y_test)
y_pred = model.predict(X_test)
loss

309/309 [==============================] - 0s 216us/step

136.1168731640072

In [15]:
# MSE btw the predicted concrete strength and its actual

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print (mse)

136.11687308115305

In [19]:
from sklearn.metrics import mean_squared_error
total_mean_squared_errors = 50
epochs = 100
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size = 0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE " +str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mserror = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mserror)
                                        
mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
sd = np.std(mean_squared_errors)
                                        
print("Mean: "+str(mean))
print("Standard Deviation: "+str(sd))

MSE 1: 31.525319985201445
MSE 2: 33.83201638008784
MSE 3: 29.682324344672047
MSE 4: 32.04108560432508
MSE 5: 32.34129384111818
MSE 6: 33.49924139374668
MSE 7: 38.665431692376494
MSE 8: 28.741531532559193
MSE 9: 28.866219628590212
MSE 10: 27.759666405835198
MSE 11: 30.510984328186627
MSE 12: 28.34024746595463
MSE 13: 33.50101697483495
MSE 14: 35.29292754139329
MSE 15: 32.47301070821324
MSE 16: 24.758119311533314
MSE 17: 29.037263043104254
MSE 18: 30.315976874342244
MSE 19: 29.91821883488627
MSE 20: 30.80023455079705
MSE 21: 28.64121962365209
MSE 22: 27.735116606777154
MSE 23: 26.181085555684604
MSE 24: 29.589591399751434
MSE 25: 31.34845242916959
MSE 26: 35.77826528950416
MSE 27: 25.514868887497
MSE 28: 28.184941733153508
MSE 29: 33.65155829272224
MSE 30: 30.89093954586288
MSE 31: 28.46689108197357
MSE 32: 26.83055403008816
MSE 33: 26.965731611529602
MSE 34: 28.431476185622724
MSE 35: 30.374768784902628
MSE 36: 33.67097330556332
MSE 37: 26.010786914516807
MSE 38: 31.57300940454971
MSE 39: 30.59076050570096
MSE 40: 25.758648486584907
MSE 41: 30.666795656519028
MSE 42: 27.31419045408181
MSE 43: 26.783295825847144
MSE 44: 31.29309021539287
MSE 45: 33.24266364582148
MSE 46: 32.101977215615676
MSE 47: 28.546971058768364
MSE 48: 30.927805829588262
MSE 49: 30.64036831655163
MSE 50: 31.72423016446308
Mean: 30.226662734446055
Standard Deviation: 2.8559182924340707

In [17]:
## Above is the mean and standard deviation of 50 mean squared errors WITH normalized data trained on 100 epochs.
## Mean = 30.226662734446055
# Standard Deviation = 2.8559182924340707

In [20]:
## Mean of the mean squared error WITH normalized data on 50 epochs  =  55.0560012109912
## Mean of the mean squared error WITH normalized date on 100 epochs =  30.226662734446055